### ISSUE TITLE
What about PsSetLoadImageNotifyRoutine ?

### ISSUE THREAD

**Issue by d-cheholia** [jxy-s/herpaderping#26]
Hello!
I apologize at once for the perhaps naive questions.

I am studying your project and found several things:

1. When PLOAD_IMAGE_NOTIFY_ROUTINE is called, I can see that my _FILE_OBJECT parameters are: 

```
  +0x04a ReadAccess : 0x1 ''
   +0x04b WriteAccess : 0x1 '' <----
   +0x04c DeleteAccess : 0 ''
   +0x04d SharedRead : 0x1 ''
   +0x04e SharedWrite : 0x1 ''
   +0x04f SharedDelete : 0x1 ''
```
You can see that WriteAccess is non-zero. In the examples from your [documentation](https://github.com/jxy-s/herpaderping/blob/main/res/DivingDeeper.md) I see that WriteAccess is  0.

My example of running a program:

`ProcessHerpaderping.exe X.exe Y.exe Z.exe`

Am I doing something wrong? 
I looked at your code and I don't think there can be `WriteAccess == 0`

<br>

2. I also noticed that when reading the PE header at the [ImageBase](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddk/ns-ntddk-_image_info) address (I can get this field in the callback) 
I am reading the original PE header (not the replaced file). 
So I can compare what's currently on the disk with what's at the `ImageBase` address. 
This will be different when  I using your current project.

My question is, are these two items proof that something went wrong with the process? (If we assume that "normal" processes for us are read-only processes)

Thank you. ❤

**Comment by jxy-s** [comment]
Indeed, those are good indicators that something wonky is happening 😄.

Yes, the same can be observed in both image load and process create. There are challenges with respect to preforming inspection during the image load notify routine. Security software has tended to avoid that path due to these challenges. Although it is possible to do so with some careful handling and some security software does. The state of the thread/process is in when the callback is invoked has changed over the years. And for which images it is invoked has also changed. More info in the [remarks section](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddk/nc-ntddk-pload_image_notify_routine) of the MSDN documentation. And see [SEC_IMAGE_NO_EXECUTE](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createfilemappinga). There is also no trivial/documented way to deny the image load from occurring in that path. In contrast, the process notify routine does expose a documented way to deny process creation. For these reasons most defensive techniques against this type of evasion occurs during inspection at the process creation routine. I'll also add there are some mini-filter callbacks for doing inspection during section creation but struggle with similar caveats/drawbacks as the image load notification (see: [IRP_MJ_ACQUIRE_FOR_SECTION_SYNCHRONIZATION](https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/flt-parameters-for-irp-mj-acquire-for-section-synchronization)).

I also recommend giving [this blog post from Microsoft](https://www.microsoft.com/security/blog/2022/06/30/using-process-creation-properties-to-catch-evasion-techniques/) a read. They outline a few indicators that I was unfamiliar with during my initial research.

**Comment by d-cheholia** [comment]
Thank you!
